version: "3.9"
services:
  sari:
    restart: always
    build: .
    networks:
      - proxynet
      - db1
    env_file:
      - .env
    volumes:
      - ./:/code
networks:
  proxynet:
    name: main
    external: true
  db1:
    name: db1
    external: true
